name: HiPlayDragon
main: pl.marcinrosol.HiplayDragon.HiplayDragon
version: 1.0
commands:
  spawn:
    description: Spawn dragon or crystal
    usage: "use /spawn"
  killdragon:
    description: Kill dragon
    usage: "use /killdragon"
  status:
    description: Game status
    usage: "use /status"