name: HiPlayDragon
main: pl.marcinrosol.HiplayDragon.HiplayDragon
version: 1.0
commands:
  dragon:
    description: Spawn dragon
    usage: "use /dragon"
  killdragon:
    description: Kill dragon
    usage: "use /killdragon"
  status:
    description: Game status
    usage: "use /status"
  crystal:
    description: Spawn ender crystal
    usage: "use /crystal"